import 'dart:convert';

import 'package:flutter/services.dart' show rootBundle;
import 'package:shared_preferences/shared_preferences.dart';

/// Loads the bundled KJV text (`assets/kjv/<bookIndex>.json`, generated by
/// tool/fetch_kjv_text.ps1). Each asset is an array of chapters, each an
/// array of verse strings. Parsed books are cached for the app's lifetime
/// (the whole Bible is only a few MB).
class BibleText {
  BibleText._();

  static final Map<int, List<List<String>>> _books = {};

  static Future<List<List<String>>> _book(int bookIndex) async {
    final cached = _books[bookIndex];
    if (cached != null) return cached;
    final raw = await rootBundle.loadString('assets/kjv/$bookIndex.json');
    final parsed = [
      for (final chapter in jsonDecode(raw) as List)
        [for (final verse in chapter as List) verse as String],
    ];
    return _books[bookIndex] = parsed;
  }

  /// Verses of the given 1-based [chapter] of the book.
  static Future<List<String>> chapterVerses(int bookIndex, int chapter) async {
    final book = await _book(bookIndex);
    return book[chapter - 1];
  }
}

/// Remembers where free reading (outside a plan) left off.
class ReadingPosition {
  ReadingPosition._();

  static const _key = 'last_read_position';

  /// Last viewed chapter as a global index, or null if never read.
  static Future<int?> load() async {
    final prefs = await SharedPreferences.getInstance();
    return prefs.getInt(_key);
  }

  static Future<void> save(int globalIndex) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setInt(_key, globalIndex);
  }
}
