# Regenerates lib/data/kjv_data.dart from the public-domain KJV text.
#
# Clones github.com/aruljohn/Bible-kjv (KJV as JSON, one file per book),
# counts the words in every chapter, and emits the Dart constant file the
# app uses to balance daily reading portions by word count.
#
# Usage:  powershell -ExecutionPolicy Bypass -File tool\generate_kjv_data.ps1

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path $PSScriptRoot -Parent
$work = Join-Path $env:TEMP "kjv-gen-$([guid]::NewGuid().ToString('n'))"

git clone --depth 1 https://github.com/aruljohn/Bible-kjv $work

try {
    $books = Get-Content "$work\Books.json" -Raw | ConvertFrom-Json
    if ($books.Count -ne 66) { throw "Expected 66 books, got $($books.Count)" }

    $counts = @()
    $totalWords = 0
    $totalChapters = 0
    foreach ($book in $books) {
        $file = Join-Path $work (($book -replace ' ', '') + '.json')
        $data = Get-Content $file -Raw | ConvertFrom-Json
        $chapterCounts = @()
        foreach ($ch in $data.chapters) {
            $words = 0
            foreach ($v in $ch.verses) {
                $tokens = $v.text -split '\s+' | Where-Object { $_ -match '\w' }
                $words += @($tokens).Count
            }
            $chapterCounts += $words
        }
        $totalWords += ($chapterCounts | Measure-Object -Sum).Sum
        $totalChapters += $chapterCounts.Count
        $counts += [pscustomobject]@{ book = $book; words = $chapterCounts }
        Write-Host "$book`: $($chapterCounts.Count) chapters"
    }
    if ($totalChapters -ne 1189) { throw "Expected 1189 chapters, got $totalChapters" }

    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine("/// KJV Bible structure and per-chapter word counts.")
    [void]$sb.AppendLine("///")
    [void]$sb.AppendLine("/// Generated by tool/generate_kjv_data.ps1 from the public-domain")
    [void]$sb.AppendLine("/// KJV text (github.com/aruljohn/Bible-kjv). Do not edit by hand.")
    [void]$sb.AppendLine("/// Totals: 66 books, $totalChapters chapters, $totalWords words.")
    [void]$sb.AppendLine("library;")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("class Book {")
    [void]$sb.AppendLine("  final String name;")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("  /// Word count of each chapter; index 0 is chapter 1.")
    [void]$sb.AppendLine("  final List<int> chapterWords;")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("  const Book(this.name, this.chapterWords);")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("  int get chapterCount => chapterWords.length;")
    [void]$sb.AppendLine("}")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("/// Books 0..38 are the Old Testament; 39..65 the New Testament.")
    [void]$sb.AppendLine("const int oldTestamentBookCount = 39;")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("const int kjvTotalChapters = $totalChapters;")
    [void]$sb.AppendLine("const int kjvTotalWords = $totalWords;")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("const List<Book> kjvBooks = [")
    foreach ($b in $counts) {
        [void]$sb.AppendLine("  Book('$($b.book)', [$($b.words -join ', ')]),")
    }
    [void]$sb.AppendLine("];")

    $out = Join-Path $repoRoot "lib\data\kjv_data.dart"
    [System.IO.File]::WriteAllText($out, $sb.ToString().Replace("`r`n", "`n"))
    Write-Host "Wrote $out — $totalChapters chapters, $totalWords words"
}
finally {
    Remove-Item $work -Recurse -Force
}
